language: php

php:
  - 7
  - 7.1
  - hhvm

sudo: false

install:
  - composer selfupdate
  - composer install
  - if [ "$TRAVIS_PHP_VERSION" == "7" ]; then composer global require --update-no-dev sugared-rim/cs satooshi/php-coveralls; fi
  - export PATH=$PATH:`composer global config bin-dir --absolute`

script:
  - composer travis
  - if [ "$TRAVIS_PHP_VERSION" == "7" ]; then composer lint; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "7" ]; then coveralls -v; fi

matrix:
  allow_failures:
    - php: hhvm
